[save_content]
INPUT_FOLDER_PATTERN = ../PublisherMetaJSONExporter_2025_08_05/europejson3/**/*.json
OUTPUT_FOLDER = output/raw/
MAX_RETRY = 2
RETRY_WAIT_TIME = 1
DIR_MAX_FILES = 300
; ONLY SWITCH CORES IF SCRAPING MANY DIFFERENT SITES! OTHERWISE MAY RUN INTO TOO MANY QUERIES!
CORES = 1
[collect_site_urls]
SITE_NAME= index.hu
INPUT_PATH=output/
NUM_WORKERS = 4